### ISSUE TITLE
Fix HTML output for documentclass book

### ISSUE THREAD

**Issue by asmaier** [arxiv-vanity/engrafo#268] opened 2018-01-04 11:40 UTC
When converting a latex document class book I found that the resulting HTML shows some problems:

    \chapter{Example}
    \section{Stuff}

is converted to

        Chapter 1 Example
    1.1 Stuff

in the HTML, but it should be converted to

    1   Chapter 1
        Example
    1.1 Stuff

Note the linebreak after Chapter 1 and the additional html anchor "1" . The same issue happens with chapters in the appendix. There is an additional problem with sections in the appendix.

    \appendix
    \chapter{Example}
    \section{Stuff}

is converted to

        Appendix A Example
    a.1 Stuff

but it should be

    A   Appendix A
        Example
    A.1 Stuff

Note the capital "A" for the html anchor before the section in the appendix.

**Comment by bfirsh** [comment] 2018-11-22 16:10
Chapter styling is fixed in new design. Appendix casing is dupe of #172. Thanks for the report!

**Closed by bfirsh** 2018-11-22 16:10 UTC
