### ISSUE TITLE
\textbf should not start a new paragraph

### ISSUE THREAD

**Issue by gauss256** [arxiv-vanity/engrafo#192] opened 2017-11-07 19:41 UTC
A `\textbf` at the beginning of a line of text gets put on a line of its own and a new paragraph is started for the text that follows. It should stay within the same paragraph.

**Comment by bfirsh** [comment] 2017-11-15 07:50
dupe of #107. Thanks for the report!

**Closed by bfirsh** 2017-11-15 07:50 UTC
